Ensure that Dockerfile_multistage builds and is runnable
It appears that the `go build` command was pointing to the wrong directory - the build was failing as follows:
```
...
 => ERROR [builder 7/8] RUN go build -ldflags="-w -s" -o /go/bin/certstream-server-go /go/src/certstream-server-go/cmd
------
 > [builder 7/8] RUN go build -ldflags="-w -s" -o /go/bin/certstream-server-go /go/src/certstream-server-go/cmd:
no Go files in /go/src/certstream-server-go/cmd
```

After it was fixed, the configfile had 0750 permissions - it was owned by root:root, thus certstream-server-go was failing to start.
```
config.go:49: Error while parsing yaml file: open /app/config.yaml: permission denied
```
This commit resolves this issue too.